### ISSUE TITLE
detecting root access

### ISSUE THREAD

**Issue by windos32** [Magisk-Modules-Alt-Repo/compatible-magisk-mirroring#1]
Hello! After installing this module (KernelSU 1.0.1 on LOS 21 or Stock Nothing ROM 2.6.0 Android 14), banking applications (MirPay, TBank and other) stop working (start detecting root access), after remove all ok...

**Comment by yzyhk904** [comment]
Sorry for late reply. This issue hasn't been notified to me automatically.

Please use Official magisk.
