### ISSUE TITLE
Found magisk

### ISSUE THREAD

**Issue by Geovanne5** [Magisk-Modules-Alt-Repo/compatible-magisk-mirroring#2]
The momo application is detecting root access to the su kernel.
When will this be fixed? 
![Screenshot_20240802_152601_KernelSU](https://github.com/user-attachments/assets/6dfac468-ec1f-496d-884b-6c9ee31bec18)
![Screenshot_20240802_152720_Momo](https://github.com/user-attachments/assets/ddc291ac-1176-4e49-9304-9466cd3a9bbc)
![Screenshot_20240802_153235_KernelSU](https://github.com/user-attachments/assets/ccebee28-a2a7-4d71-8a7a-a22b6fb4fbea)

**Comment by yzyhk904** [comment]
Please use official magisk.
